printf "\n\n\n"
printf "                                   __  \n"
printf "                                  / _)  "
printf "                           .-^^^-/ /  \n"
printf "                        __/       /  \n"
printf "                       <__.|_|-|_|  \n"
printf "\n\n\t\t\t"
printf "\n\n"
